title: 创意冲浪社                        # title of the site
description: 带着创意，去冲浪，去实现          # description of the site
url: https://surf-the-internet-community.lin037.cn/       # domain
baseurl: /                     # root directory

# Email address
email: 2869199723@qq.com

# Path of site resources
img: /assets/img 
css: /assets/css  
js:  /assets/js  
cdn: https://cdn.jsdelivr.net/gh/professordeng/simple@gh-pages/assets/img

## Docs: https://pages.github.com/versions/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-paginate

# paginate setting
paginate: 5

# Comment system
## Docs: https://github.com/gitalk/gitalk/blob/master/readme.md
gitalk:
  enable: true 
  clientID: edc63f2073dc1f2000fe
  clientSecret: ad62728d9ee9f887bbdfa312afaa288cebb5379e
  repo: blog_comment
  owner: surf-the-internet-community
  admin: surf-the-internet-community
  id: location.pathname      # The default is location.pathname
  

# Google Analytics
## Docs: https://analytics.google.com/analytics/web/
google-analytics: 

# default layout of the articles in _post
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
