# Customize site navigation
nav:
- name: 首页
  url: /
- name: 档案
  url: /archives.html
- name: 关于
  url: /about.html

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- icon: github
  link: https://github.com/surf-the-internet-community/surf-the-internet-community.github.io
- icon: false    # weibo
  link: https://weibo.com/codeng
- icon: false
  link: https://t.me/jekyll_simple
- icon: false
  link: https://zhihu.com/people/professordeng
- icon: false
  link: https://linkedin.com/in/professordeng
  
# Customize site text
prev: 上一页
next: 下一页

prev_page: 上一页
next_page: 下一页

search_tip: 在此输入搜索内容
searching: 搜索中

new: 新建

read_more: 查看更多

edit: 创意冲浪社
